Upd

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,7 +40,7 @@ jobs:
       run: |
         sudo mkdir -p /opt/android-sdk
         sudo mkdir -p /opt/android-ndk
-        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O android-sdk.zip
+        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android-sdk.zip
         unzip android-sdk.zip -d /opt/android-sdk/cmdline-tools
         mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
 
@@ -48,7 +48,22 @@ jobs:
       run: |
         echo "Installing SDK packages"
         yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
-        /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529" "cmdline-tools;latest" "tools" "build-tools;30.0.3" "platforms;android-30"
+        /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529" "cmdline-tools;latest" "tools"
+
+    - name: Verify Java installation
+      run: java -version
+
+    - name: Verify sdkmanager installation
+      run: /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --list
+
+    - name: Verify AIDL installation
+      run: |
+        if [ -f "/opt/android-sdk/build-tools/30.0.3/aidl" ]; then
+          echo "AIDL found"
+        else
+          echo "AIDL not found"
+          exit 1
+        fi
 
     - name: Install Buildozer and dependencies
       run: |
